use super::role_labels_extra::PERFORMER_ROLE_LABELS_EXTRA;

pub(crate) fn performer_role_labels() -> impl Iterator<Item = &'static (&'static str, &'static str)>
{
    PERFORMER_ROLE_LABELS
        .iter()
        .chain(PERFORMER_ROLE_LABELS_EXTRA.iter())
}

static PERFORMER_ROLE_LABELS: &[(&str, &str)] = &[
    ("a&R", "Artists and Repertoire"),
    ("a&RDirector", "Artists and Repertoire Director"),
    ("aAndRCoordinator", "A&R Coordinator"),
    ("accordion", "Accordion"),
    ("acousticGuitar", "Acoustic Guitar"),
    ("additionalEngineer", "Additional Engineer"),
    ("additionalKeyboard", "Additional Keyboard"),
    ("additionalMusic", "Additional Music"),
    ("additionalProduction", "Additional Production"),
    ("additionalProgrammer", "Additional Programmer"),
    ("additionalStudioProducer", "Additional Studio Producer"),
    ("additionalVocalist", "Additional Vocalist"),
    ("additionalVocals", "Additional Vocals"),
    ("arranger", "Arranger"),
    ("artDirector", "Art Director"),
    ("artist", "Artist"),
    ("assistant", "Assistant"),
    ("assistantEngineer", "Assistant Engineer"),
    ("assistantMixer", "Assistant Mixer"),
    ("assistantMixingEngineer", "Assistant Mixing Engineer"),
    ("associatedPerformer", "Associated Performer"),
    ("associatedProducer", "Associated Producer"),
    ("author", "Author"),
    ("backingVocals", "Backing Vocals"),
    ("backgroundVocal", "Background Vocal"),
    ("backgroundVocalist", "Background Vocalist"),
    ("backgroundVocals", "Background Vocals"),
    ("baritoneSaxophone", "Baritone Saxophone"),
    ("bass", "Bass"),
    ("bassGuitar", "Bass Guitar"),
    ("celesta", "Celesta"),
    ("cello", "Cello"),
    ("chamberOrchestra", "Chamber Orchestra"),
    ("choir", "Choir"),
    ("choirArranger", "Choir Arranger"),
    ("choirConductor", "Choir Conductor"),
    ("coachVocals", "Coach Vocals"),
    ("composer", "Composer"),
    ("composerLyricist", "Composer Lyricist"),
    ("conductor", "Conductor"),
    ("consultant", "Consultant"),
    ("contractor", "Contractor"),
    ("coProducer", "Co-Producer"),
    ("designer", "Designer"),
    ("digitalEditingEngineer", "Digital Editing Engineer"),
    ("doubleBass", "Double Bass"),
    ("drum", "Drum"),
    ("drumMachine", "Drum Machine"),
    ("drumProgrammer", "Drum Programmer"),
    ("drumProgramming", "Drum Programming"),
    ("drumKit", "Drum Kit"),
    ("drums", "Drums"),
    ("editingEngineer", "Editing Engineer"),
    ("electricBassGuitar", "Electric Bass Guitar"),
    ("electricGuitar", "Electric Guitar"),
    ("engineer", "Engineer"),
    ("executiveProducer", "Executive Producer"),
    ("featuredArtist", "Featured Artist"),
    ("fiddle", "Fiddle"),
    ("frenchHorn", "French Horn"),
    ("glockenspiel", "Glockenspiel"),
    ("guitar", "Guitar"),
    ("hammondOrgan", "Hammond Organ"),
    ("harp", "Harp"),
    ("horn", "Horn"),
    ("horns", "Horns"),
    ("instrumentation", "Instrumentation"),
    ("keyboard", "Keyboard"),
    ("keyboards", "Keyboards"),
    ("leadGuitar", "Lead Guitar"),
    ("leadViolin", "Lead Violin"),
    ("leadVocals", "Lead Vocals"),
    ("lyricist", "Lyricist"),
    ("mainArtist", "Main Artist"),
    ("manager", "Manager"),
    ("masterer", "Masterer"),
    ("masteringEngineer", "Mastering Engineer"),
    ("mixer", "Mixer"),
    ("mixEngineer", "Mix Engineer"),
    ("mixingEngineer", "Mixing Engineer"),
    ("mixingSecondEngineer", "Mixing Second Engineer"),
    ("music", "Music"),
    ("musicDirector", "Music Director"),
    ("musicEditor", "Music Editor"),
    ("musicPublisher", "Music Publisher"),
    ("musicSupervisor", "Music Supervisor"),
];
