//! Second half of the Qobuz performer role label table — split out of
//! `role_labels.rs` purely to stay under the file line budget. See
//! `performer_role_labels()` in `role_labels.rs` for the combined iterator.

pub(super) static PERFORMER_ROLE_LABELS_EXTRA: &[(&str, &str)] = &[
    ("nylonStringGuitar", "Nylon String Guitar"),
    ("orchestra", "Orchestra"),
    ("orchestralContractor", "Orchestral Contractor"),
    ("orchestration", "Orchestration"),
    ("organ", "Organ"),
    ("other", "Other"),
    ("oud", "Oud"),
    ("percussion", "Percussion"),
    ("performance", "Performance"),
    ("performer", "Performer"),
    ("piano", "Piano"),
    ("producer", "Producer"),
    ("production", "Production"),
    ("programmer", "Programmer"),
    ("programming", "Programming"),
    ("programmingEngineer", "Programming Engineer"),
    ("rapVocalist", "Rap Vocalist"),
    ("recordedby", "Recorded By"),
    ("recordingArranger", "Recording Arranger"),
    ("recordingEngineer", "Recording Engineer"),
    ("recordingProducer", "Recording Producer"),
    ("recordingSecondEngineer", "Recording Second Engineer"),
    ("remasteringEngineer", "Remastering Engineer"),
    ("remixer", "Remixer"),
    ("remixingSecondEngineer", "Remixing Second Engineer"),
    ("rhythmGuitar", "rhythmGuitar"),
    ("samples", "Samples"),
    ("saxophone", "Saxophone"),
    ("secondEngineer", "Second Engineer"),
    ("singer", "Singer"),
    ("slideguitar&Pad", "Slide Guitar & Pad"),
    ("songwriter", "Songwriter"),
    ("stringArranger", "String Arranger"),
    ("strings", "Strings"),
    ("studioAssistant", "Studio Assistant"),
    ("studioPersonnel", "Studio Personnel"),
    ("synthesizer", "Synthesizer"),
    ("synthesizerProgrammer", "Synthesizer Programmer"),
    ("synthesizerProgramming", "Synthesizer Programming"),
    ("technicalAssistant", "Technical Assistant"),
    ("technicalEngineer", "Technical Engineer"),
    ("technician", "Technician"),
    ("trombone", "Trombone"),
    ("trumpet", "Trumpet"),
    ("tuba", "Tuba"),
    ("ukulele", "Ukulele"),
    ("unknown", "Unknown"),
    ("vibraphone", "Vibraphone"),
    ("viola", "Viola"),
    ("violin", "Violin"),
    ("vocal", "Vocal"),
    ("vocalArranger", "Vocal Arranger"),
    ("vocalEditingEngineer", "Vocal Editing Engineer"),
    ("vocalEngineer", "Vocal Engineer"),
    ("vocalProducer", "Vocal Producer"),
    ("vocalist", "Vocalist"),
    ("vocals", "Vocals"),
    ("vocals&Guitar", "Vocals & Guitar"),
    ("voice", "Voice"),
    ("workArranger", "Work Arranger"),
    ("writer", "Writer"),
];
