//! Data only: the named-entity → char table and the bare (no-semicolon)
//! allowlist. Kept separate from `entities.rs` so future additions to the
//! table are a single-file diff.

/// Named entities → their (single) character. Semicolon-terminated form
/// only; the bare tolerance is limited to `BARE_NAMES`.
pub(super) const NAMED: &[(&str, char)] = &[
    // Core escapes
    ("amp", '&'),
    ("lt", '<'),
    ("gt", '>'),
    ("quot", '"'),
    ("apos", '\''),
    ("nbsp", ' '),
    // Symbols
    ("copy", '\u{00A9}'),
    ("reg", '\u{00AE}'),
    ("trade", '\u{2122}'),
    ("deg", '\u{00B0}'),
    ("middot", '\u{00B7}'),
    ("bull", '\u{2022}'),
    ("sect", '\u{00A7}'),
    ("para", '\u{00B6}'),
    ("plusmn", '\u{00B1}'),
    ("times", '\u{00D7}'),
    ("divide", '\u{00F7}'),
    ("euro", '\u{20AC}'),
    ("pound", '\u{00A3}'),
    ("cent", '\u{00A2}'),
    ("yen", '\u{00A5}'),
    // Dashes / ellipsis / quotes
    ("mdash", '\u{2014}'),
    ("ndash", '\u{2013}'),
    ("hellip", '\u{2026}'),
    ("ldquo", '\u{201C}'),
    ("rdquo", '\u{201D}'),
    ("lsquo", '\u{2018}'),
    ("rsquo", '\u{2019}'),
    ("laquo", '\u{00AB}'),
    ("raquo", '\u{00BB}'),
    // Latin-1 accented, lowercase
    ("agrave", '\u{00E0}'),
    ("aacute", '\u{00E1}'),
    ("acirc", '\u{00E2}'),
    ("atilde", '\u{00E3}'),
    ("auml", '\u{00E4}'),
    ("aring", '\u{00E5}'),
    ("aelig", '\u{00E6}'),
    ("ccedil", '\u{00E7}'),
    ("egrave", '\u{00E8}'),
    ("eacute", '\u{00E9}'),
    ("ecirc", '\u{00EA}'),
    ("euml", '\u{00EB}'),
    ("igrave", '\u{00EC}'),
    ("iacute", '\u{00ED}'),
    ("icirc", '\u{00EE}'),
    ("iuml", '\u{00EF}'),
    ("ntilde", '\u{00F1}'),
    ("ograve", '\u{00F2}'),
    ("oacute", '\u{00F3}'),
    ("ocirc", '\u{00F4}'),
    ("otilde", '\u{00F5}'),
    ("ouml", '\u{00F6}'),
    ("oslash", '\u{00F8}'),
    ("ugrave", '\u{00F9}'),
    ("uacute", '\u{00FA}'),
    ("ucirc", '\u{00FB}'),
    ("uuml", '\u{00FC}'),
    ("yacute", '\u{00FD}'),
    ("yuml", '\u{00FF}'),
    ("szlig", '\u{00DF}'),
    ("oelig", '\u{0153}'),
    // Latin-1 accented, uppercase
    ("Agrave", '\u{00C0}'),
    ("Aacute", '\u{00C1}'),
    ("Acirc", '\u{00C2}'),
    ("Atilde", '\u{00C3}'),
    ("Auml", '\u{00C4}'),
    ("Aring", '\u{00C5}'),
    ("AElig", '\u{00C6}'),
    ("Ccedil", '\u{00C7}'),
    ("Egrave", '\u{00C8}'),
    ("Eacute", '\u{00C9}'),
    ("Ecirc", '\u{00CA}'),
    ("Euml", '\u{00CB}'),
    ("Igrave", '\u{00CC}'),
    ("Iacute", '\u{00CD}'),
    ("Icirc", '\u{00CE}'),
    ("Iuml", '\u{00CF}'),
    ("Ntilde", '\u{00D1}'),
    ("Ograve", '\u{00D2}'),
    ("Oacute", '\u{00D3}'),
    ("Ocirc", '\u{00D4}'),
    ("Otilde", '\u{00D5}'),
    ("Ouml", '\u{00D6}'),
    ("Oslash", '\u{00D8}'),
    ("Ugrave", '\u{00D9}'),
    ("Uacute", '\u{00DA}'),
    ("Ucirc", '\u{00DB}'),
    ("Uuml", '\u{00DC}'),
    ("Yacute", '\u{00DD}'),
    ("OElig", '\u{0152}'),
];

/// Entities the Qobuz API emits WITHOUT the trailing semicolon (the TiVo
/// `&copy  Name /TiVo` credit line). Kept deliberately tiny — every name
/// added here widens the false-positive surface on plain-text ampersands.
pub(super) const BARE_NAMES: &[&str] = &["copy", "reg", "amp", "nbsp"];
